spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kwakkwak?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: sksmsdit12@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto : update
    properties :
      hibernate :
        show_sql : true
        format_sql : true